// Code generated by Kitex v0.12.3. DO NOT EDIT.

package stockservice

import (
	"context"
	"errors"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	stock "seckill/idl/kitex_gen/stock"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"QueryStock": kitex.NewMethodInfo(
		queryStockHandler,
		newStockServiceQueryStockArgs,
		newStockServiceQueryStockResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"PreDeductStock": kitex.NewMethodInfo(
		preDeductStockHandler,
		newStockServicePreDeductStockArgs,
		newStockServicePreDeductStockResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"RollbackStock": kitex.NewMethodInfo(
		rollbackStockHandler,
		newStockServiceRollbackStockArgs,
		newStockServiceRollbackStockResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
}

var (
	stockServiceServiceInfo                = NewServiceInfo()
	stockServiceServiceInfoForClient       = NewServiceInfoForClient()
	stockServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return stockServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return stockServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return stockServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "StockService"
	handlerType := (*stock.StockService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "stock",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.12.3",
		Extra:           extra,
	}
	return svcInfo
}

func queryStockHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*stock.StockServiceQueryStockArgs)
	realResult := result.(*stock.StockServiceQueryStockResult)
	success, err := handler.(stock.StockService).QueryStock(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newStockServiceQueryStockArgs() interface{} {
	return stock.NewStockServiceQueryStockArgs()
}

func newStockServiceQueryStockResult() interface{} {
	return stock.NewStockServiceQueryStockResult()
}

func preDeductStockHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*stock.StockServicePreDeductStockArgs)
	realResult := result.(*stock.StockServicePreDeductStockResult)
	success, err := handler.(stock.StockService).PreDeductStock(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newStockServicePreDeductStockArgs() interface{} {
	return stock.NewStockServicePreDeductStockArgs()
}

func newStockServicePreDeductStockResult() interface{} {
	return stock.NewStockServicePreDeductStockResult()
}

func rollbackStockHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*stock.StockServiceRollbackStockArgs)
	realResult := result.(*stock.StockServiceRollbackStockResult)
	success, err := handler.(stock.StockService).RollbackStock(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newStockServiceRollbackStockArgs() interface{} {
	return stock.NewStockServiceRollbackStockArgs()
}

func newStockServiceRollbackStockResult() interface{} {
	return stock.NewStockServiceRollbackStockResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) QueryStock(ctx context.Context, req *stock.StockReq) (r *stock.StockResp, err error) {
	var _args stock.StockServiceQueryStockArgs
	_args.Req = req
	var _result stock.StockServiceQueryStockResult
	if err = p.c.Call(ctx, "QueryStock", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) PreDeductStock(ctx context.Context, req *stock.StockReq) (r *stock.StockResp, err error) {
	var _args stock.StockServicePreDeductStockArgs
	_args.Req = req
	var _result stock.StockServicePreDeductStockResult
	if err = p.c.Call(ctx, "PreDeductStock", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) RollbackStock(ctx context.Context, req *stock.StockReq) (r *stock.StockResp, err error) {
	var _args stock.StockServiceRollbackStockArgs
	_args.Req = req
	var _result stock.StockServiceRollbackStockResult
	if err = p.c.Call(ctx, "RollbackStock", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
